# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('comment', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='django_comments.Comment')),
            ],
        ),
    ]
